name: 'analytics'               
version: '1.0.0'                
config-version: 2               

profile: 'analytics'

model-paths: ["models"]         
analysis-paths: ["analyses"]    
test-paths: ["tests"]           
seed-paths: ["data"]            
macro-paths: ["macros"]         
snapshot-paths: ["snapshots"]   

target-path: "target"           
clean-targets:                  
  - "target"
  - "dbt_packages"

models:
  analytics:                    
    staging:
      materialized: view        
      schema: staging           
    